@startuml
left to right direction

actor "Utente" as U

rectangle "Funzionalità Utente" {
  usecase "Accesso e dashboard" as UC1
  usecase "Gestione stanze (CRUD)" as UC2
  usecase "Gestione dispositivi (CRUD)" as UC3
  usecase "Controllo dispositivi" as UC4
  usecase "Gestione automazioni (CRUD)" as UC5
  usecase "Monitoraggio e statistiche" as UC8
  usecase "Registrazione eventi di sistema" as UCE1
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5

UC4 ..> UCE1 : <<include>>
UC5 ..> UCE1 : <<include>>
UC8 ..> UCE1 : <<include>>

@enduml
