@startuml
  title Diagramma Attivita - Consultazione storico eventi

  start
    :Aprire storico eventi;
    :Impostare filtri;
    :Ricercare eventi su repository;
    :Mostrare risultati;
  if (Richiesta esportazione?) then (Si)
    :Generare file log;
    :Scaricare file;
  else (No)
  endif
  stop
@enduml
